# -*- coding: utf-8 -*-
"""TDS_GA8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b4PjkExomnpcEAZVQcMPqGrfnYm9gl-k
"""

pip install streamlit

import streamlit as st
import pandas as pd
from sklearn import datasets
from sklearn.ensemble import RandomForestClassifier
import pickle

st.write("""
# Find largest of three numbers
""")
#Get Input

st.header('User Input Parameters')

def user_input_features():
    number_1 = st.number_input("NUMBER_1",min_value=0,max_value=100,step=1)
    number_2 = st.number_input("NUMBER_2",min_value=0,max_value=100,step=1)
    number_3 = st.number_input("NUMBER_3",min_value=0,max_value=100,step=1)
    data = {'NUMBER_1': number_1,'NUMBER_2': number_2,'NUMBER_1': number_3}
    features = pd.DataFrame(data, index=[0])
    return features

df = user_input_features()

st.subheader('User Input parameters')
st.write(df.to_dict())

if (number_1 >= number_2) and (number_1 >= number_3):
    largest = number_1
elif (number_2 >= number_1) and (number_2 >= number_3):
    largest = number_2
else:
    largest = number_3

# display result
st.write("""
# The largest number =
""", largest)
#print('The largest number = ', largest)